
# https://docs.google.com/document/d/1rgtaHhQDl98GBrfc4OJiwZy2CtWkDD3H7RGy0dXnm4g/edit#


language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
    
# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest
  # - py.test -v --color=yes --exitfirst --showlocals --durations=5



# script:
#   - pytest

# docker image build -t ${IMGNAME} .
# docker run my/mqtt-subscriber 

# script:
#   # Travis CI seems to be coming in on undocumented IP addresss. 
#   - dig +short myip.opendns.com @resolver1.openends.com 


# after_success:
#   - docker login -u ${DHUB_USERNAME} -p ${DHUB_PASS}    # login to docker hub and push docker image 
#   - echo
#   - chmod
#   - ssh -o 
#   - ssh -o 